const actionsTypes = Object.freeze({
  PROCESS_LOGIN: "PROCESS_LOGIN",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",

  GET_ALL_POSTS: "GET_ALL_POSTS",

  GET_ALL_SUGGEST_USER: "GET_ALL_SUGGEST_USER",
  GET_ALL_USER_FOLLOWED: "GET_ALL_USER_FOLLOWED",

  GET_ALL_USER_CONTACT: "GET_ALL_USER_CONTACT",

  GET_ALL_CONVERSATIONS: "GET_ALL_CONVERSATIONS",
  GET_ALL_CHATS: "GET_ALL_CHATS",

  COUNT: "COUNT",
});

export default actionsTypes;
